#!/usr/bin/env bash
# Display a story for each user described in /etc/passwd

while IFS=: read -r username password uid gid info home shell
do
    printf "The user %s is part of the %s gang, lives in %s and rides %s. %s's place is protected by the passcode %s, more info about the user here: %s\n" \
        "$username" "$gid" "$home" "$shell" "$uid" "$password" "$info"
done < /etc/passwd

