#!/usr/bin/env bash
# Loop from 1 to 10 and print messages for the 4th, 8th and other iterations

i=1
while [ "$i" -le 10 ]; do
  if [ "$i" -eq 4 ]; then
    echo "bad luck"
  elif [ "$i" -eq 8 ]; then
    echo "good luck"
  else
    echo "Best School"
  fi
  i=$((i + 1))
done
