#!/usr/bin/env bash
# Display numbers from 1 to 20 with superstitious messages for specific numbers

i=1
while [ "$i" -le 20 ]; do
    printf '%s\n' "$i"
    case "$i" in
        4)
            printf '%s\n' "bad luck from China"
            ;;
        9)
            printf '%s\n' "bad luck from Japan"
            ;;
        17)
            printf '%s\n' "bad luck from Italy"
            ;;
        *)
            ;;
    esac
    i=$((i + 1))
done
