#!/usr/bin/env bash
# Creates a PID file, prints messages forever and reacts to signals.

PID_FILE="/var/run/myscript.pid"

cleanup() {
    if [ -f "$PID_FILE" ]; then
        current_pid=""
        current_pid="$(<"$PID_FILE")"
        if [ "$current_pid" = "$$" ]; then
            rm -f "$PID_FILE"
        fi
    fi
}

sigint_handler() {
    echo "Y U no love me?!"
}

sigterm_handler() {
    echo "I hate the kill command"
    cleanup
    exit 0
}

sigquit_handler() {
    cleanup
    exit 0
}

trap sigint_handler INT
trap sigterm_handler TERM
trap sigquit_handler QUIT

# Write our PID to the PID file
echo "$$" > "$PID_FILE"

# Print forever
while true; do
    echo "To infinity and beyond"
    sleep 2
done
