#!/usr/bin/env bash
# Displays "To infinity and beyond" indefinitely and reacts to SIGTERM.

# When the script receives SIGTERM, print "I am invincible!!!" but do NOT exit
trap 'echo "I am invincible!!!"' SIGTERM

while true
do
    echo "To infinity and beyond"
    sleep 2
done
